#!/bin/bash
# Use the ps command with options to show all processes, for all users, including those which might not have a TTY
# -a: show all processes
# -x: display in a user-oriented format
# -u: show process hierarchy
ps -axuf

