#!/bin/bash

# create the pid file
echo $$ > /var/run/myscript.pid

# trap signals
trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

