#!/usr/bin/env bash

# Get the process id of the script
pid=$(ps -ef | grep "4-to_infinity_and_beyond" | grep -v "grep" | awk '{print $2}')

# Send a TERM signal to the process
kill -TERM $pid

echo "4-to_infinity_and_beyond process has been stopped"

