#!/usr/bin/env bash

# Get the process id of the script
pid=$(ps -ef | grep "7-highlander" | grep -v "grep" | awk '{print $2}')

# Send a TERM signal to the process
kill -TERM $pid

echo "7-highlander process has been stopped"

