#!/bin/env bash
#This script configures an Ubuntu server with the below requirements

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root"
  exit 1
fi

sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /etc/hosts

echo "8.8.8.8 facebook.com" >> /etc/hosts

systemctl restart NetworkManager

