#!/usr/bin/env bash
#Write a Bash script that displays all active IPv4 IPs on the machine it's executed on.
interfaces=$(ifconfig | awk -F':' '/^[a-z]/ && !/^lo/ {print $1}')

# Iterate over each network interface
for interface in $interfaces
do
  # Get the IPv4 address of the current interface
  ip=$(ifconfig $interface | awk '/inet / {print $2}')

  # Print the IP if it's not empty
  if [ -n "$ip" ]
  then
    echo $ip
  fi
done

