#!/bin/env bash
# this script that displays all active IPv4 on the machine it is executed

interfaces=$(ifconfig | grep -Eo '^\w+')

# Loop through each network interface
for interface in $interfaces
do
  # Get the IPv4 IP address of the interface
  ip=$(ifconfig $interface | grep 'inet ' | awk '{print $2}')
  # If an IPv4 IP address is found, print it
  if [ ! -z "$ip" ]; then
    echo $ip
  fi
done

